workflows:
  ios-unsigned:
    name: Build Unsigned IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build unsigned IPA
        script: |
          flutter build ios --release --no-codesign
          cd ios
          # Create archive
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -destination generic/platform=iOS -archivePath build/Runner.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          # Export IPA
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportPath build/ios -exportOptionsPlist exportOptions.plist
          cd ..
          # Also create a manual IPA as backup
          cd ios
          mkdir -p Payload
          cp -r ../build/ios/Release-iphoneos/Runner.app Payload/
          zip -r ../build/ios/Runner-manual.ipa Payload
          rm -rf Payload
          cd ..
    artifacts:
      - ios/build/ios/*.ipa
      - build/ios/Runner-manual.ipa
      - build/ios/Release-iphoneos/Runner.app 