workflows:
  ios-unsigned:
    name: Build Unsigned IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build unsigned IPA
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa 